<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();
        $cities = array(
        array('name' => "Bombuflat",'state_id' => 1),
        array('name' => "Garacharma",'state_id' => 1),
        array('name' => "Port Blair",'state_id' => 1),
        array('name' => "Rangat",'state_id' => 1),
        array('name' => "Addanki",'state_id' => 2),
        array('name' => "Adivivaram",'state_id' => 2),
        array('name' => "Adoni",'state_id' => 2),
        array('name' => "Sirpur",'state_id' => 2),
        array('name' => "Sirsilla",'state_id' => 2),
        array('name' => "Sompeta",'state_id' => 2),
        array('name' => "Tadpatri",'state_id' => 2),
        array('name' => "Tallapalle",'state_id' => 2),
        array('name' => "Tanuku",'state_id' => 2),
        array('name' => "Basar",'state_id' => 3),
        array('name' => "Bondila",'state_id' => 3),
        array('name' => "Changlang",'state_id' => 3),
        array('name' => "Daporijo",'state_id' => 3),
        array('name' => "Deomali",'state_id' => 3),
        array('name' => "Niz-Hajo",'state_id' => 4),
        array('name' => "North Guwahati",'state_id' => 4),
        array('name' => "Numaligarh",'state_id' => 4),
        array('name' => "Titabor",'state_id' => 4),
        array('name' => "Udalguri",'state_id' => 4),
        array('name' => "Umrangso",'state_id' => 4),
        array('name' => "Uttar Krishnapur Part-I",'state_id' => 4),
        array('name' => "Amarpur",'state_id' => 5),
        array('name' => "Ara",'state_id' => 5),
        array('name' => "Araria",'state_id' => 5),
        array('name' => "Areraj",'state_id' => 5),
        array('name' => "Asarganj",'state_id' => 5),
        array('name' => "Aurangabad",'state_id' => 5),
        array('name' => "Bihar Sharif",'state_id' => 5),
        array('name' => "Bihariganj",'state_id' => 5),
        array('name' => "Bikramganj",'state_id' => 5),
        array('name' => "Jamalpur",'state_id' => 5),
        array('name' => "Jamhaur",'state_id' => 5),
        array('name' => "Jamui",'state_id' => 5),
        array('name' => "Janakpur Road",'state_id' => 5),
        array('name' => "Janpur",'state_id' => 5),
        array('name' => "Jaynagar",'state_id' => 5),
        array('name' => "Jha Jha",'state_id' => 5),
        array('name' => "Jhanjharpur",'state_id' => 5),
        array('name' => "Patna",'state_id' => 5),
        array('name' => "Phulwari",'state_id' => 5),
        array('name' => "Piro",'state_id' => 5),
        array('name' => "Purnia",'state_id' => 5),
        array('name' => "Pusa",'state_id' => 5),
        array('name' => "Rafiganj",'state_id' => 5),
        array('name' => "Raghunathpur",'state_id' => 5),
        array('name' => "Rajgir",'state_id' => 5),
        array('name' => "Ramnagar",'state_id' => 5),
        array('name' => "Teghra",'state_id' => 5),
        array('name' => "Tekari",'state_id' => 5),
        array('name' => "Thakurganj",'state_id' => 5),
        array('name' => "Vaishali",'state_id' => 5),
        array('name' => "Waris Aliganj",'state_id' => 5),
        array('name' => "Chandigarh",'state_id' => 6),
        array('name' => "Ahiwara",'state_id' => 7),
        array('name' => "Akaltara",'state_id' => 7),
        array('name' => "Ambagarh Chauki",'state_id' => 7),
        array('name' => "Ambikapur",'state_id' => 7),
        array('name' => "Arang",'state_id' => 7),
        array('name' => "Bade Bacheli",'state_id' => 7),
        array('name' => "Bagbahara",'state_id' => 7),
        array('name' => "Baikunthpur",'state_id' => 7),
        array('name' => "Balod",'state_id' => 7),
        array('name' => "Dipka",'state_id' => 7),
        array('name' => "Mehmand",'state_id' => 7),
        array('name' => "Mongra",'state_id' => 7),
        array('name' => "Mowa",'state_id' => 7),
        array('name' => "Mungeli",'state_id' => 7),
        array('name' => "Nailajanjgir",'state_id' => 7),
        array('name' => "Namna Kalan",'state_id' => 7),
        array('name' => "Naya Baradwar",'state_id' => 7),
        array('name' => "Pandariya",'state_id' => 7),
        array('name' => "Sirgiti",'state_id' => 7),
        array('name' => "Takhatpur",'state_id' => 7),
        array('name' => "Telgaon",'state_id' => 7),
        array('name' => "Tildanewra",'state_id' => 7),
        array('name' => "Urla",'state_id' => 7),
        array('name' => "Vishrampur",'state_id' => 7),
        array('name' => "Amli",'state_id' => 8),
        array('name' => "Silvassa",'state_id' => 8),
        array('name' => "Daman",'state_id' => 9),
        array('name' => "Diu",'state_id' => 9),
        array('name' => "Delhi",'state_id' => 10),
        array('name' => "New Delhi",'state_id' => 10),
        array('name' => "Aldona",'state_id' => 11),
        array('name' => "Altinho",'state_id' => 11),
        array('name' => "Aquem",'state_id' => 11),
        array('name' => "Arpora",'state_id' => 11),
        array('name' => "Bambolim",'state_id' => 11),
        array('name' => "Bandora",'state_id' => 11),

        array('name' => "Tivim",'state_id' => 11),
        array('name' => "Valpoi",'state_id' => 11),
        array('name' => "Varca",'state_id' => 11),
        array('name' => "Vasco",'state_id' => 11),
        array('name' => "Verna",'state_id' => 11),
        array('name' => "Abrama",'state_id' => 12),
        array('name' => "Adalaj",'state_id' => 12),
        array('name' => "Adityana",'state_id' => 12),
        array('name' => "Advana",'state_id' => 12),
        array('name' => "Ahmedabad",'state_id' => 12),
        array('name' => "Ahwa",'state_id' => 12),
        array('name' => "Alang",'state_id' => 12),
        array('name' => "Ambaji",'state_id' => 12),
        array('name' => "Ambaliyasan",'state_id' => 12),
        array('name' => "Amod",'state_id' => 12),
        array('name' => "Amreli",'state_id' => 12),
        array('name' => "Amroli",'state_id' => 12),
        array('name' => "Anand",'state_id' => 12),
        array('name' => "Andada",'state_id' => 12),
        array('name' => "Anjar",'state_id' => 12),
        array('name' => "Anklav",'state_id' => 12),
        array('name' => "Ankleshwar",'state_id' => 12),
        array('name' => "Anklesvar INA",'state_id' => 12),
        array('name' => "Antaliya",'state_id' => 12),
        array('name' => "Arambhada",'state_id' => 12),
        array('name' => "Asarma",'state_id' => 12),
        array('name' => "Wankaner",'state_id' => 12),
        array('name' => "Zalod",'state_id' => 12),
        array('name' => "Ambala",'state_id' => 13),
        array('name' => "Ambala Cantt",'state_id' => 13),
        array('name' => "Uklana Mandi",'state_id' => 13),
        array('name' => "Uncha Siwana",'state_id' => 13),
        array('name' => "Yamunanagar",'state_id' => 13),
        array('name' => "Arki",'state_id' => 14),
        array('name' => "Baddi",'state_id' => 14),
        array('name' => "Bakloh",'state_id' => 14),
        array('name' => "Banjar",'state_id' => 14),
        array('name' => "Bhota",'state_id' => 14),
        array('name' => "Bhuntar",'state_id' => 14),
        array('name' => "Bilaspur",'state_id' => 14),
        array('name' => "Chamba",'state_id' => 14),
        array('name' => "Chaupal",'state_id' => 14),
        array('name' => "Chuari Khas",'state_id' => 14),
        array('name' => "Dagshai",'state_id' => 14),
        array('name' => "Dalhousie",'state_id' => 14),
        array('name' => "Dalhousie Cantonment",'state_id' => 14),
        array('name' => "Damtal",'state_id' => 14),
        array('name' => "Daulatpur",'state_id' => 14),
        array('name' => "Dera Gopipur",'state_id' => 14),
        array('name' => "Dhalli",'state_id' => 14),
        array('name' => "Solan",'state_id' => 14),
        array('name' => "Solon",'state_id' => 14),
        array('name' => "Sundarnagar",'state_id' => 14),
        array('name' => "Sundernagar",'state_id' => 14),
        array('name' => "Talai",'state_id' => 14),
        array('name' => "Theog",'state_id' => 14),
        array('name' => "Tira Sujanpur",'state_id' => 14),
        array('name' => "Una",'state_id' => 14),
        array('name' => "Yol",'state_id' => 14),
        array('name' => "Achabal",'state_id' => 15),
        array('name' => "Akhnur",'state_id' => 15),
        array('name' => "Anantnag",'state_id' => 15),
        array('name' => "Arnia",'state_id' => 15),
        array('name' => "Tral",'state_id' => 15),
        array('name' => "Udhampur",'state_id' => 15),
        array('name' => "Uri",'state_id' => 15),
        array('name' => "Vijaypur",'state_id' => 15),
        array('name' => "Adityapur",'state_id' => 16),
        array('name' => "Amlabad",'state_id' => 16),
        array('name' => "Angarpathar",'state_id' => 16),
        array('name' => "Ara",'state_id' => 16),
        array('name' => "Tisra",'state_id' => 16),
        array('name' => "Topa",'state_id' => 16),
        array('name' => "Topchanchi",'state_id' => 16),
        array('name' => "Adityanagar",'state_id' => 17),
        array('name' => "Adityapatna",'state_id' => 17),
        array('name' => "Afzalpur",'state_id' => 17),
        array('name' => "Ajjampur",'state_id' => 17),
        array('name' => "Yelbarga",'state_id' => 17),
        array('name' => "Yellapur",'state_id' => 17),
        array('name' => "Yenagudde",'state_id' => 17),
        array('name' => "Adimaly",'state_id' => 19),
        array('name' => "Adoor",'state_id' => 19),
        array('name' => "Adur",'state_id' => 19),
        array('name' => "Akathiyur",'state_id' => 19),
        array('name' => "Alangad",'state_id' => 19),
        array('name' => "Alappuzha",'state_id' => 19),
        array('name' => "Aluva",'state_id' => 19),
        array('name' => "Ancharakandy",'state_id' => 19),
        array('name' => "Angamaly",'state_id' => 19),
        array('name' => "Aroor",'state_id' => 19),
        array('name' => "Arukutti",'state_id' => 19),
        array('name' => "Attingal",'state_id' => 19),
        array('name' => "Avinissery",'state_id' => 19),
        array('name' => "Azhikode North",'state_id' => 19),
        array('name' => "Azhikode South",'state_id' => 19),
        array('name' => "Azhiyur",'state_id' => 19),
        array('name' => "Balussery",'state_id' => 19),
        array('name' => "Bangramanjeshwar",'state_id' => 19),
        array('name' => "Beypur",'state_id' => 19),
        array('name' => "Brahmakulam",'state_id' => 19),
        array('name' => "Chala",'state_id' => 19),
        array('name' => "Chalakudi",'state_id' => 19),
        array('name' => "Changanacheri",'state_id' => 19),
        array('name' => "Chauwara",'state_id' => 19),
        array('name' => "Chavakkad",'state_id' => 19),
        array('name' => "Chelakkara",'state_id' => 19),
        array('name' => "Chelora",'state_id' => 19),
        array('name' => "Chendamangalam",'state_id' => 19),
        array('name' => "Chengamanad",'state_id' => 19),
        array('name' => "Chengannur",'state_id' => 19),
        array('name' => "Cheranallur",'state_id' => 19),
        array('name' => "Cheriyakadavu",'state_id' => 19),
        array('name' => "Cherthala",'state_id' => 19),
        array('name' => "Cherukunnu",'state_id' => 19),
        array('name' => "Cheruthazham",'state_id' => 19),
        array('name' => "Cheruvannur",'state_id' => 19),
        array('name' => "Cheruvattur",'state_id' => 19),
        array('name' => "Chevvur",'state_id' => 19),
        array('name' => "Chirakkal",'state_id' => 19),
        array('name' => "Chittur",'state_id' => 19),
        array('name' => "Chockli",'state_id' => 19),
        array('name' => "Churnikkara",'state_id' => 19),
        array('name' => "Villiappally",'state_id' => 19),
        array('name' => "Wayanad",'state_id' => 19),
        array('name' => "Agethi",'state_id' => 20),
        array('name' => "Amini",'state_id' => 20),
        array('name' => "Androth Island",'state_id' => 20),
        array('name' => "Kavaratti",'state_id' => 20),
        array('name' => "Minicoy",'state_id' => 20),
        array('name' => "Agar",'state_id' => 21),
        array('name' => "Ajaigarh",'state_id' => 21),
        array('name' => "Akoda",'state_id' => 21),
        array('name' => "Tirodi",'state_id' => 21),
        array('name' => "Udaipura",'state_id' => 21),
        array('name' => "Ujjain",'state_id' => 21),
        array('name' => "Ukwa",'state_id' => 21),
        array('name' => "Umaria",'state_id' => 21),
        array('name' => "Unchahara",'state_id' => 21),
        array('name' => "Unhel",'state_id' => 21),
        array('name' => "Vehicle Factory Jabalpur",'state_id' => 21),
        array('name' => "Vidisha",'state_id' => 21),
        array('name' => "Vijayraghavgarh",'state_id' => 21),
        array('name' => "Waraseoni",'state_id' => 21),
        array('name' => "Achalpur",'state_id' => 22),
        array('name' => "Aheri",'state_id' => 22),
        array('name' => "Ahmadnagar Cantonment",'state_id' => 22),
        array('name' => "Ahmadpur",'state_id' => 22),
        array('name' => "Ahmednagar",'state_id' => 22),
        array('name' => "Ajra",'state_id' => 22),
        array('name' => "Akalkot",'state_id' => 22),
        array('name' => "Akkalkuwa",'state_id' => 22),
        array('name' => "Akola",'state_id' => 22),
        array('name' => "Akot",'state_id' => 22),
        array('name' => "Alandi",'state_id' => 22),
        array('name' => "Alibag",'state_id' => 22),
        array('name' => "Yaval",'state_id' => 22),
        array('name' => "Yavatmal",'state_id' => 22),
        array('name' => "Yeola",'state_id' => 22),
        array('name' => "Yerkheda",'state_id' => 22),
        array('name' => "Andro",'state_id' => 23),
        array('name' => "Bijoy Govinda",'state_id' => 23),
        array('name' => "Bishnupur",'state_id' => 23),
        array('name' => "Churachandpur",'state_id' => 23),
        array('name' => "Heriok",'state_id' => 23),
        array('name' => "Imphal",'state_id' => 23),
        array('name' => "Jiribam",'state_id' => 23),
        array('name' => "Kakching",'state_id' => 23),
        array('name' => "Kakching Khunou",'state_id' => 23),
        array('name' => "Khongman",'state_id' => 23),
        array('name' => "Kumbi",'state_id' => 23),
        array('name' => "Kwakta",'state_id' => 23),
        array('name' => "Lamai",'state_id' => 23),
        array('name' => "Lamjaotongba",'state_id' => 23),
        array('name' => "Lamshang",'state_id' => 23),
        array('name' => "Lilong",'state_id' => 23),
        array('name' => "Mayang Imphal",'state_id' => 23),
        array('name' => "Moirang",'state_id' => 23),
        array('name' => "Moreh",'state_id' => 23),
        array('name' => "Nambol",'state_id' => 23),
        array('name' => "Naoriya Pakhanglakpa",'state_id' => 23),
        array('name' => "Ningthoukhong",'state_id' => 23),
        array('name' => "Oinam",'state_id' => 23),
        array('name' => "Porompat",'state_id' => 23),
        array('name' => "Samurou",'state_id' => 23),
        array('name' => "Sekmai Bazar",'state_id' => 23),
        array('name' => "Senapati",'state_id' => 23),
        array('name' => "Sikhong Sekmai",'state_id' => 23),
        array('name' => "Sugnu",'state_id' => 23),
        array('name' => "Thongkhong Laxmi Bazar",'state_id' => 23),
        array('name' => "Thoubal",'state_id' => 23),
        array('name' => "Torban",'state_id' => 23),
        array('name' => "Wangjing",'state_id' => 23),
        array('name' => "Wangoi",'state_id' => 23),
        array('name' => "Yairipok",'state_id' => 23),
        array('name' => "Baghmara",'state_id' => 24),
        array('name' => "Cherrapunji",'state_id' => 24),
        array('name' => "Jawai",'state_id' => 24),
        array('name' => "Madanrting",'state_id' => 24),
        array('name' => "Mairang",'state_id' => 24),
        array('name' => "Mawlai",'state_id' => 24),
        array('name' => "Nongmynsong",'state_id' => 24),
        array('name' => "Nongpoh",'state_id' => 24),
        array('name' => "Nongstoin",'state_id' => 24),
        array('name' => "Nongthymmai",'state_id' => 24),
        array('name' => "Pynthorumkhrah",'state_id' => 24),
        array('name' => "Resubelpara",'state_id' => 24),
        array('name' => "Shillong",'state_id' => 24),
        array('name' => "Shillong Cantonment",'state_id' => 24),
        array('name' => "Tura",'state_id' => 24),
        array('name' => "Williamnagar",'state_id' => 24),
        array('name' => "Aizawl",'state_id' => 25),
        array('name' => "Bairabi",'state_id' => 25),
        array('name' => "Biate",'state_id' => 25),
        array('name' => "Champhai",'state_id' => 25),
        array('name' => "Darlawn",'state_id' => 25),
        array('name' => "Hnahthial",'state_id' => 25),
        array('name' => "Kawnpui",'state_id' => 25),
        array('name' => "Khawhai",'state_id' => 25),
        array('name' => "Khawzawl",'state_id' => 25),
        array('name' => "Kolasib",'state_id' => 25),
        array('name' => "Lengpui",'state_id' => 25),
        array('name' => "Lunglei",'state_id' => 25),
        array('name' => "Mamit",'state_id' => 25),
        array('name' => "North Vanlaiphai",'state_id' => 25),
        array('name' => "Saiha",'state_id' => 25),
        array('name' => "Sairang",'state_id' => 25),
        array('name' => "Saitul",'state_id' => 25),
        array('name' => "Serchhip",'state_id' => 25),
        array('name' => "Thenzawl",'state_id' => 25),
        array('name' => "Tlabung",'state_id' => 25),
        array('name' => "Vairengte",'state_id' => 25),
        array('name' => "Zawlnuam",'state_id' => 25),
        array('name' => "Chumukedima",'state_id' => 26),
        array('name' => "Dimapur",'state_id' => 26),
        array('name' => "Kohima",'state_id' => 26),
        array('name' => "Mokokchung",'state_id' => 26),
        array('name' => "Mon",'state_id' => 26),
        array('name' => "Phek",'state_id' => 26),
        array('name' => "Tuensang",'state_id' => 26),
        array('name' => "Wokha",'state_id' => 26),
        array('name' => "Zunheboto",'state_id' => 26),
        array('name' => "Anandapur",'state_id' => 29),
        array('name' => "Angul",'state_id' => 29),
        array('name' => "Aska",'state_id' => 29),
        array('name' => "Athgarh",'state_id' => 29),
        array('name' => "Athmallik",'state_id' => 29),
        array('name' => "Balagoda",'state_id' => 29),
        array('name' => "Balangir",'state_id' => 29),
        array('name' => "Balasore",'state_id' => 29),
        array('name' => "Baleshwar",'state_id' => 29),
        array('name' => "Balimeta",'state_id' => 29),
        array('name' => "Balugaon",'state_id' => 29),
        array('name' => "Banapur",'state_id' => 29),
        array('name' => "Bangura",'state_id' => 29),
        array('name' => "Banki",'state_id' => 29),
        array('name' => "Banposh",'state_id' => 29),
        array('name' => "Barbil",'state_id' => 29),
        array('name' => "Bargarh",'state_id' => 29),
        array('name' => "Baripada",'state_id' => 29),
        array('name' => "Barpali",'state_id' => 29),
        array('name' => "Sorada",'state_id' => 29),
        array('name' => "Soro",'state_id' => 29),
        array('name' => "Sunabeda",'state_id' => 29),
        array('name' => "Sundargarh",'state_id' => 29),
        array('name' => "Talcher",'state_id' => 29),
        array('name' => "Talcher Thermal Power Station ",'state_id' => 29),
        array('name' => "Tarabha",'state_id' => 29),
        array('name' => "Tensa",'state_id' => 29),
        array('name' => "Titlagarh",'state_id' => 29),
        array('name' => "Udala",'state_id' => 29),
        array('name' => "Udayagiri",'state_id' => 29),
        array('name' => "Umarkot",'state_id' => 29),
        array('name' => "Vikrampur",'state_id' => 29),
        array('name' => "Ariankuppam",'state_id' => 31),
        array('name' => "Karaikal",'state_id' => 31),
        array('name' => "Kurumbapet",'state_id' => 31),
        array('name' => "Mahe",'state_id' => 31),
        array('name' => "Ozhukarai",'state_id' => 31),
        array('name' => "Pondicherry",'state_id' => 31),
        array('name' => "Villianur",'state_id' => 31),
        array('name' => "Yanam",'state_id' => 31),
        array('name' => "Abohar",'state_id' => 32),
        array('name' => "Adampur",'state_id' => 32),
        array('name' => "Ahmedgarh",'state_id' => 32),
        array('name' => "Ajnala",'state_id' => 32),
        array('name' => "Akalgarh",'state_id' => 32),
        array('name' => "Alawalpur",'state_id' => 32),
        array('name' => "Amloh",'state_id' => 32),
        array('name' => "Amritsar",'state_id' => 32),
        array('name' => "Amritsar Cantonment",'state_id' => 32),
        array('name' => "Anandpur Sahib",'state_id' => 32),
        array('name' => "Badhni Kalan",'state_id' => 32),
        array('name' => "Bagh Purana",'state_id' => 32),
        array('name' => "Balachaur",'state_id' => 32),
        array('name' => "Banaur",'state_id' => 32),
        array('name' => "Banga",'state_id' => 32),
        array('name' => "Banur",'state_id' => 32),
        array('name' => "Baretta",'state_id' => 32),
        array('name' => "Bariwala",'state_id' => 32),
        array('name' => "Sham Churasi",'state_id' => 32),
        array('name' => "Shekhpura",'state_id' => 32),
        array('name' => "Sirhind",'state_id' => 32),
        array('name' => "Sri Hargobindpur",'state_id' => 32),
        array('name' => "Sujanpur",'state_id' => 32),
        array('name' => "Sultanpur Lodhi",'state_id' => 32),
        array('name' => "Sunam",'state_id' => 32),
        array('name' => "Talwandi Bhai",'state_id' => 32),
        array('name' => "Talwara",'state_id' => 32),
        array('name' => "Tappa",'state_id' => 32),
        array('name' => "Tarn Taran",'state_id' => 32),
        array('name' => "Urmar Tanda",'state_id' => 32),
        array('name' => "Zira",'state_id' => 32),
        array('name' => "Zirakpur",'state_id' => 32),
        array('name' => "Abu Road",'state_id' => 33),
        array('name' => "Ajmer",'state_id' => 33),
        array('name' => "Aklera",'state_id' => 33),
        array('name' => "Alwar",'state_id' => 33),
        array('name' => "Amet",'state_id' => 33),
        array('name' => "Antah",'state_id' => 33),
        array('name' => "Anupgarh",'state_id' => 33),
        array('name' => "Asind",'state_id' => 33),
        array('name' => "Bagar",'state_id' => 33),
        array('name' => "Bagru",'state_id' => 33),
        array('name' => "Bahror",'state_id' => 33),
        array('name' => "Bakani",'state_id' => 33),
        array('name' => "Todra",'state_id' => 33),
        array('name' => "Tonk",'state_id' => 33),
        array('name' => "Udaipur",'state_id' => 33),
        array('name' => "Udpura",'state_id' => 33),
        array('name' => "Uniara",'state_id' => 33),
        array('name' => "Vanasthali",'state_id' => 33),
        array('name' => "Vidyavihar",'state_id' => 33),
        array('name' => "Vijainagar",'state_id' => 33),
        array('name' => "Viratnagar",'state_id' => 33),
        array('name' => "Wer",'state_id' => 33),
        array('name' => "Gangtok",'state_id' => 34),
        array('name' => "Gezing",'state_id' => 34),
        array('name' => "Jorethang",'state_id' => 34),
        array('name' => "Mangan",'state_id' => 34),
        array('name' => "Namchi",'state_id' => 34),
        array('name' => "Naya Bazar",'state_id' => 34),
        array('name' => "No City",'state_id' => 34),
        array('name' => "Rangpo",'state_id' => 34),
        array('name' => "Sikkim",'state_id' => 34),
        array('name' => "Singtam",'state_id' => 34),
        array('name' => "Upper Tadong",'state_id' => 34),
        array('name' => "Abiramam",'state_id' => 35),
        array('name' => "Achampudur",'state_id' => 35),
        array('name' => "Acharapakkam",'state_id' => 35),
        array('name' => "Acharipallam",'state_id' => 35),
        array('name' => "Achipatti",'state_id' => 35),
        array('name' => "Adikaratti",'state_id' => 35),
        array('name' => "Adiramapattinam",'state_id' => 35),
        array('name' => "Aduturai",'state_id' => 35),
        array('name' => "Adyar",'state_id' => 35),
        array('name' => "Virudhachalam",'state_id' => 35),
        array('name' => "Virudhunagar",'state_id' => 35),
        array('name' => "Virupakshipuram",'state_id' => 35),
        array('name' => "Viswanatham",'state_id' => 35),
        array('name' => "Vriddhachalam",'state_id' => 35),
        array('name' => "Walajabad",'state_id' => 35),
        array('name' => "Walajapet",'state_id' => 35),
        array('name' => "Wellington",'state_id' => 35),
        array('name' => "Yercaud",'state_id' => 35),
        array('name' => "Zamin Uthukuli",'state_id' => 35),
        array('name' => "Achampet",'state_id' => 36),
        array('name' => "Adilabad",'state_id' => 36),
        array('name' => "Vikarabad",'state_id' => 36),
        array('name' => "Wanaparthy",'state_id' => 36),
        array('name' => "Warangal",'state_id' => 36),
        array('name' => "Yellandu",'state_id' => 36),
        array('name' => "Zahirabad",'state_id' => 36),
        array('name' => "Agartala",'state_id' => 37),
        array('name' => "Amarpur",'state_id' => 37),
        array('name' => "Ambassa",'state_id' => 37),
        array('name' => "Badharghat",'state_id' => 37),
        array('name' => "Belonia",'state_id' => 37),
        array('name' => "Dharmanagar",'state_id' => 37),
        array('name' => "Gakulnagar",'state_id' => 37),
        array('name' => "Gandhigram",'state_id' => 37),
        array('name' => "Indranagar",'state_id' => 37),
        array('name' => "Jogendranagar",'state_id' => 37),
        array('name' => "Kailasahar",'state_id' => 37),
        array('name' => "Kamalpur",'state_id' => 37),
        array('name' => "Kanchanpur",'state_id' => 37),
        array('name' => "Khowai",'state_id' => 37),
        array('name' => "Kumarghat",'state_id' => 37),
        array('name' => "Kunjaban",'state_id' => 37),
        array('name' => "Narsingarh",'state_id' => 37),
        array('name' => "Pratapgarh",'state_id' => 37),
        array('name' => "Ranir Bazar",'state_id' => 37),
        array('name' => "Sabrum",'state_id' => 37),
        array('name' => "Sonamura",'state_id' => 37),
        array('name' => "Teliamura",'state_id' => 37),
        array('name' => "Udaipur",'state_id' => 37),
        array('name' => "Achhalda",'state_id' => 38),
        array('name' => "Achhnera",'state_id' => 38),
        array('name' => "Adari",'state_id' => 38),
        array('name' => "Afzalgarh",'state_id' => 38),
        array('name' => "Agarwal Mandi",'state_id' => 38),
        array('name' => "Agra",'state_id' => 38),
        array('name' => "Agra Cantonment",'state_id' => 38),    
        array('name' => "Ugu",'state_id' => 38),
        array('name' => "Ujhani",'state_id' => 38),
        array('name' => "Ujhari",'state_id' => 38),
        array('name' => "Umri",'state_id' => 38),
        array('name' => "Umri Kalan",'state_id' => 38),
        array('name' => "Un",'state_id' => 38),
        array('name' => "Unchahar",'state_id' => 38),
        array('name' => "Unnao",'state_id' => 38),
        array('name' => "Usaihat",'state_id' => 38),
        array('name' => "Usawan",'state_id' => 38),
        array('name' => "Utraula",'state_id' => 38),
        array('name' => "Varanasi",'state_id' => 38),
        array('name' => "Varanasi Cantonment",'state_id' => 38),
        array('name' => "Vijaigarh",'state_id' => 38),
        array('name' => "Vrindavan",'state_id' => 38),
        array('name' => "Wazirganj",'state_id' => 38),
        array('name' => "Zafarabad",'state_id' => 38),
        array('name' => "Zaidpur",'state_id' => 38),
        array('name' => "Zamania",'state_id' => 38),
        array('name' => "Almora",'state_id' => 39),
        array('name' => "Almora Cantonment",'state_id' => 39),
        array('name' => "Shaktigarh",'state_id' => 39),
        array('name' => "Sitarganj",'state_id' => 39),
        array('name' => "Srinagar",'state_id' => 39),
        array('name' => "Sultanpur",'state_id' => 39),
        array('name' => "Tanakpur",'state_id' => 39),
        array('name' => "Tehri",'state_id' => 39),
        array('name' => "Udham Singh Nagar",'state_id' => 39),
        array('name' => "Uttarkashi",'state_id' => 39),
        array('name' => "Vikasnagar",'state_id' => 39),
        array('name' => "Virbhadra",'state_id' => 39),        
        array('name' => "Nabagram",'state_id' => 41),
        array('name' => "Nabgram",'state_id' => 41),
        array('name' => "Nachhratpur Katabari",'state_id' => 41),
        array('name' => "Nadia",'state_id' => 41),
        array('name' => "Naihati",'state_id' => 41),
        array('name' => "Nalhati",'state_id' => 41),
        array('name' => "Nasra",'state_id' => 41),
        array('name' => "Natibpur",'state_id' => 41),
        array('name' => "Naupala",'state_id' => 41),
        array('name' => "Navadwip",'state_id' => 41),
        array('name' => "Nebadhai Duttapukur",'state_id' => 41),
        array('name' => "New Barrackpore",'state_id' => 41),
        array('name' => "Ni Barakpur",'state_id' => 41),
        array('name' => "Nibra",'state_id' => 41),
        array('name' => "Noapara",'state_id' => 41),
        array('name' => "Nokpul",'state_id' => 41),
        array('name' => "Raghudebpur",'state_id' => 41),
        array('name' => "Shankhanagar",'state_id' => 41),
        array('name' => "Shantipur",'state_id' => 41),
        array('name' => "Shrirampur",'state_id' => 41),
        array('name' => "Siduli",'state_id' => 41),
        array('name' => "Siliguri",'state_id' => 41),
        array('name' => "Simla",'state_id' => 41),
        array('name' => "Singur",'state_id' => 41),
        array('name' => "Sirsha",'state_id' => 41),
        array('name' => "Siuri",'state_id' => 41),
        array('name' => "Sobhaganj",'state_id' => 41),
        array('name' => "Sodpur",'state_id' => 41),
        array('name' => "Sonamukhi",'state_id' => 41),
        array('name' => "Eshkashem",'state_id' => 42),
        array('name' => "Fayzabad",'state_id' => 42),
        array('name' => "Jurm",'state_id' => 42),
        array('name' => "Khandud",'state_id' => 42),
        array('name' => "Qal'eh-ye Panjeh",'state_id' => 42),
        array('name' => "Bala Morghab",'state_id' => 43),
        array('name' => "Qal'eh-ye Naw",'state_id' => 43),
        array('name' => "Andarab",'state_id' => 44),
        array('name' => "Baghlan",'state_id' => 44),
        array('name' => "Dahaneh-ye Ghawri",'state_id' => 44),
        array('name' => "Nahrin",'state_id' => 44),
        array('name' => "Pol-e Khumri",'state_id' => 44),
        array('name' => "Balkh",'state_id' => 45),
        array('name' => "Dawlatabad",'state_id' => 45),
        array('name' => "Mazar-e Sharif",'state_id' => 45),
        array('name' => "Qarchi Gak",'state_id' => 45),
        array('name' => "Shulgara",'state_id' => 45),
        array('name' => "Tash Gozar",'state_id' => 45),
        array('name' => "Bamiyan",'state_id' => 46),
        array('name' => "Panjab",'state_id' => 46),
        array('name' => "Qil Qal'eh",'state_id' => 46),
        array('name' => "Anar Darreh",'state_id' => 47),
        array('name' => "Farah",'state_id' => 47),
        array('name' => "Shindand",'state_id' => 47),
        array('name' => "Andkhvoy",'state_id' => 48),
        array('name' => "Darzi Ab",'state_id' => 48),
        array('name' => "Dawlatabad",'state_id' => 48),
        array('name' => "Maymanah",'state_id' => 48),
        array('name' => "Chaghcharan",'state_id' => 49),
        array('name' => "Shahrak",'state_id' => 49),
        array('name' => "Taywarah",'state_id' => 49),
        array('name' => "Ghazni",'state_id' => 50),
        array('name' => "Awbeh",'state_id' => 51),
        array('name' => "Eslam Qal'eh",'state_id' => 51),
        array('name' => "Ghurian",'state_id' => 51),
        array('name' => "Herat",'state_id' => 51),
        array('name' => "Karukh",'state_id' => 51),
        array('name' => "Kuhestan",'state_id' => 51),
        array('name' => "Zendejan",'state_id' => 51),
        array('name' => "Baghran",'state_id' => 52),
        array('name' => "Darwishan",'state_id' => 52),
        array('name' => "Deh Shu",'state_id' => 52),
        array('name' => "Gereshk",'state_id' => 52),
        array('name' => "Lashkar Gah",'state_id' => 52),
        array('name' => "Sangin",'state_id' => 52),
        array('name' => "Aqchah",'state_id' => 53),
        array('name' => "Qarqin",'state_id' => 53),
        array('name' => "Sang-e Charak",'state_id' => 53),
        array('name' => "Shibarghan",'state_id' => 53),
        array('name' => "Baghrami",'state_id' => 54),
        array('name' => "Kabul",'state_id' => 54),
        array('name' => "Mir Bachchekut",'state_id' => 54),
        array('name' => "Paghman",'state_id' => 54),
        array('name' => "Qarabagh",'state_id' => 54),
        array('name' => "Sarawbi",'state_id' => 54),
        array('name' => "Mahmud-e Raqi",'state_id' => 55),
        array('name' => "Taghab",'state_id' => 55),
        array('name' => "Khawst",'state_id' => 56),
        array('name' => "Asadabad",'state_id' => 57),
        array('name' => "Asmar",'state_id' => 57),
        array('name' => "Mehtar Lam",'state_id' => 58),
        array('name' => "Azraw",'state_id' => 59),
        array('name' => "Baraki Barak",'state_id' => 59),
        array('name' => "Pol-e Alam",'state_id' => 59),
        array('name' => "Achin",'state_id' => 60),
        array('name' => "Batsawul",'state_id' => 60),
        array('name' => "Hugyani",'state_id' => 60),
        array('name' => "Jalalabad",'state_id' => 60),
        array('name' => "Nader Shah Kawt",'state_id' => 60),
        array('name' => "Chahar Burjak",'state_id' => 61),
        array('name' => "Chakhansur",'state_id' => 61),
        array('name' => "Khash",'state_id' => 61),
        array('name' => "Mirabad",'state_id' => 61),
        array('name' => "Rudbar",'state_id' => 61),
        array('name' => "Zaranj",'state_id' => 61),
        array('name' => "Nuristan",'state_id' => 62),
        array('name' => "Orgun",'state_id' => 63),
        array('name' => "Zareh Sharan",'state_id' => 63),
        array('name' => "Zarghun Shahr",'state_id' => 63),
        array('name' => "'Ali Khayl",'state_id' => 64),
        array('name' => "Ghardez",'state_id' => 64),
        array('name' => "Charikar",'state_id' => 65),
        array('name' => "Jabal-os-Saraj",'state_id' => 65),
        array('name' => "Qandahar",'state_id' => 66),
        array('name' => "Dasht-e Archa",'state_id' => 67),
        array('name' => "Emam Saheb",'state_id' => 67),
        array('name' => "Qal'eh-ye Zal",'state_id' => 67),
        array('name' => "Qunduz",'state_id' => 67),
        array('name' => "Aybak",'state_id' => 68),
        array('name' => "Kholm",'state_id' => 68),
        array('name' => "Chah Ab",'state_id' => 70),
        array('name' => "Eshkamesh",'state_id' => 70),
        array('name' => "Farkhar",'state_id' => 70),
        array('name' => "Khwajeh Ghar",'state_id' => 70),
        array('name' => "Rostaq",'state_id' => 70),
        array('name' => "Taloqan",'state_id' => 70),
        array('name' => "Yangi Qal'eh",'state_id' => 70),
        array('name' => "Deh Rawud",'state_id' => 71),
        array('name' => "Gaz Ab",'state_id' => 71),
        array('name' => "Tarin Kawt",'state_id' => 71),
        array('name' => "Uruzgan",'state_id' => 71),
        array('name' => "Gardan Diwal",'state_id' => 72),
        array('name' => "Maydanshahr",'state_id' => 72),
        array('name' => "Qalat-e Ghilzay",'state_id' => 73),
        array('name' => "Berat",'state_id' => 74),
        array('name' => "Polican",'state_id' => 74),
        array('name' => "Ure Vajgurore",'state_id' => 74),
        array('name' => "Bulqize",'state_id' => 75),
        array('name' => "Delvine",'state_id' => 76),
        array('name' => "Bilisht",'state_id' => 77),
        array('name' => "Maqellare",'state_id' => 78),
        array('name' => "Peshkopi",'state_id' => 78),
        array('name' => "Durres",'state_id' => 79),
        array('name' => "Shijak",'state_id' => 79),
        array('name' => "Cerrik",'state_id' => 80),
        array('name' => "Elbasan",'state_id' => 80),
        array('name' => "Kerrabe",'state_id' => 80),
        array('name' => "Fier",'state_id' => 81),
        array('name' => "Patos",'state_id' => 81),
        array('name' => "Roskovec",'state_id' => 81),
        array('name' => "Gjirokaster",'state_id' => 82),
        array('name' => "Libohove",'state_id' => 82),
        array('name' => "Gramsh",'state_id' => 83),
        array('name' => "Krume",'state_id' => 84),
        array('name' => "Kavaje",'state_id' => 85),
        array('name' => "Erseke",'state_id' => 86),
        array('name' => "Leskovik",'state_id' => 86),
        array('name' => "Korce",'state_id' => 87),
        array('name' => "Maliq",'state_id' => 87),
        array('name' => "Fushe-Kruje",'state_id' => 88),
        array('name' => "Kruje",'state_id' => 88),
        array('name' => "Mamurras",'state_id' => 88),
        array('name' => "Milot",'state_id' => 88),
        array('name' => "Kucove",'state_id' => 89),
        array('name' => "Kukes",'state_id' => 90),
        array('name' => "Lac",'state_id' => 91),
        array('name' => "Lezhe",'state_id' => 92),
        array('name' => "Shengjin",'state_id' => 92),
        array('name' => "Librazhd",'state_id' => 93),
        array('name' => "Perrenjas",'state_id' => 93),
        array('name' => "Lushnje",'state_id' => 94),
        array('name' => "Rrogozhine",'state_id' => 94),
        array('name' => "Ballsh",'state_id' => 95),
        array('name' => "Burrel",'state_id' => 97),
        array('name' => "Klos",'state_id' => 97),
        array('name' => "Kraste",'state_id' => 97),
        array('name' => "Ulze",'state_id' => 97),
        array('name' => "Kurbnesh",'state_id' => 98),
        array('name' => "Rreshen",'state_id' => 98),
        array('name' => "Rubik",'state_id' => 98),
        array('name' => "Peqin",'state_id' => 99),
        array('name' => "Kelcyre",'state_id' => 100),
        array('name' => "Permet",'state_id' => 100),
        array('name' => "Pogradec",'state_id' => 101),
        array('name' => "Fierze",'state_id' => 102),
        array('name' => "Fushe-Arrez",'state_id' => 102),
        array('name' => "Puke",'state_id' => 102),
        array('name' => "Konispol",'state_id' => 103),
        array('name' => "Sarande",'state_id' => 103),
        array('name' => "Shkoder",'state_id' => 104),
        array('name' => "Corovode",'state_id' => 105),
        array('name' => "Memaliaj",'state_id' => 106),
        array('name' => "Tepelene",'state_id' => 106),
        array('name' => "Kamze",'state_id' => 107),
        array('name' => "Paskuqan",'state_id' => 107),
        array('name' => "Tirane",'state_id' => 107),
        array('name' => "Vore",'state_id' => 107),
        array('name' => "Bajram Curri",'state_id' => 108),
        array('name' => "Himare",'state_id' => 109),
        array('name' => "Orikum",'state_id' => 109),
        array('name' => "Selenice",'state_id' => 109),
        array('name' => "Vlore",'state_id' => 109),
        array('name' => "Adrar",'state_id' => 112),
        array('name' => "Awlaf",'state_id' => 112),
        array('name' => "Rijan",'state_id' => 112),
        array('name' => "Timimun",'state_id' => 112),
        array('name' => "Hydra",'state_id' => 113),
        array('name' => "Kouba",'state_id' => 113),
        array('name' => "Annabah",'state_id' => 114),
        array('name' => "Birrahhal",'state_id' => 114),
        array('name' => "Saraydih",'state_id' => 114),
        array('name' => "Sidi Amar",'state_id' => 114),
        array('name' => "al-Buni",'state_id' => 114),
        array('name' => "al-Hajar",'state_id' => 114),
        array('name' => "'Abadlah",'state_id' => 115),
        array('name' => "Bani Wanif",'state_id' => 115),
        array('name' => "Bashshar",'state_id' => 115),
        array('name' => "Qanadsan",'state_id' => 115),
        array('name' => "Taghit",'state_id' => 115),
        array('name' => "'Aris",'state_id' => 116),
        array('name' => "'Ayn Tutah",'state_id' => 116),
        array('name' => "Barikah",'state_id' => 116),
        array('name' => "Batnah",'state_id' => 116),
        array('name' => "Marwanah",'state_id' => 116),
        array('name' => "Naghaus",'state_id' => 116),
        array('name' => "Ra's-al-'Ayun",'state_id' => 116),
        array('name' => "Tazult",'state_id' => 116),
        array('name' => "'Ayt Rizin",'state_id' => 117),
        array('name' => "Akbu",'state_id' => 117),
        array('name' => "Amizur",'state_id' => 117),
        array('name' => "Barbasha",'state_id' => 117),
        array('name' => "al-Qasr",'state_id' => 117),
        array('name' => "Awlad Jallal",'state_id' => 118),
        array('name' => "Biskrah",'state_id' => 118),
        array('name' => "Sidi Khalid",'state_id' => 118),
        array('name' => "Sidi Ukbah",'state_id' => 118),
        array('name' => "Tulja",'state_id' => 118),
        array('name' => "Um'ash",'state_id' => 118),
        array('name' => "Zaribat-al-Wad",'state_id' => 118),
        array('name' => "Awlad Salam",'state_id' => 119),
        array('name' => "Awlad Yaysh",'state_id' => 119),
        array('name' => "Aghbalu",'state_id' => 120),
        array('name' => "Bi'r Ghabalu",'state_id' => 120),
        array('name' => "Buirah",'state_id' => 120),
        array('name' => "Lakhdariyah",'state_id' => 120),
        array('name' => "Shurfa",'state_id' => 120),
        array('name' => "Sur-al-Ghuzlan",'state_id' => 120),
        array('name' => "'Ayn Tayah",'state_id' => 121),
        array('name' => "Budwawu",'state_id' => 121),
        array('name' => "Budwawu al-Bahri",'state_id' => 121),
        array('name' => "Bumardas",'state_id' => 121),
        array('name' => "Burj Minayal",'state_id' => 121),
        array('name' => "Dalis",'state_id' => 121),
        array('name' => "Hammadi",'state_id' => 121),
        array('name' => "Issar",'state_id' => 121),
        array('name' => "ar-Ruwibah",'state_id' => 121),
        array('name' => "Ammi Mussa",'state_id' => 123),
        array('name' => "Ghalizan",'state_id' => 123),
        array('name' => "Jidiwiyah",'state_id' => 123),
        array('name' => "Mazunah",'state_id' => 123),
        array('name' => "Sidi Muhammad Ban 'Ali",'state_id' => 123),
        array('name' => "Wadi Rahiyu",'state_id' => 123),
        array('name' => "Zammurah",'state_id' => 123),
        array('name' => "Biryan",'state_id' => 124),
        array('name' => "Bu Nura",'state_id' => 124),
        array('name' => "Ghardaia",'state_id' => 124),
        array('name' => "Ghardayah",'state_id' => 124),
        array('name' => "Matlili",'state_id' => 124),
        array('name' => "al-Ghuli'ah",'state_id' => 124),
        array('name' => "al-Qararah",'state_id' => 124),
        array('name' => "Ilizi",'state_id' => 125),
        array('name' => "Amir 'Abd-al-Qadar",'state_id' => 126),
        array('name' => "Jijili",'state_id' => 126),
        array('name' => "Shifka",'state_id' => 126),
        array('name' => "Tahar",'state_id' => 126),
        array('name' => "al-Miliyah",'state_id' => 126),
        array('name' => "'Ayn Wissarah",'state_id' => 127),
        array('name' => "'Ayn-al-Ibil",'state_id' => 127),
        array('name' => "Birin",'state_id' => 127),
        array('name' => "Dar Shiyukh",'state_id' => 127),
        array('name' => "Hassi Bahbah",'state_id' => 127),
        array('name' => "Jilfah",'state_id' => 127),
        array('name' => "Mis'ad",'state_id' => 127),
        array('name' => "Sharif",'state_id' => 127),
        array('name' => "al-Idrisiyah",'state_id' => 127),
        array('name' => "Khanshalah",'state_id' => 128),
        array('name' => "Sharshar",'state_id' => 128),
        array('name' => "Tawziyanat",'state_id' => 128),
        array('name' => "al-Mahmal",'state_id' => 128),
        array('name' => "'Ayn-al-Hajal",'state_id' => 129),
        array('name' => "'Ayn-al-Milh",'state_id' => 129),
        array('name' => "Bu Sa'adah",'state_id' => 129),
        array('name' => "Hammam Dhala'a",'state_id' => 129),
        array('name' => "Ma'adid",'state_id' => 129),
        array('name' => "Maghra",'state_id' => 129),
        array('name' => "Masilah",'state_id' => 129),
        array('name' => "Sidi 'Aysa",'state_id' => 129),
        array('name' => "Wanugha",'state_id' => 129),
        array('name' => "'Ayn Bu Sif",'state_id' => 130),
        array('name' => "Birwaghiyah",'state_id' => 130),
        array('name' => "Midyah",'state_id' => 130),
        array('name' => "Qasr-al-Bukhari",'state_id' => 130),
        array('name' => "Shillalah",'state_id' => 130),
        array('name' => "Tablat",'state_id' => 130),
        array('name' => "Farjiwah",'state_id' => 131),
        array('name' => "Milah",'state_id' => 131),
        array('name' => "Qararam Quqa",'state_id' => 131),
        array('name' => "Ruwashad",'state_id' => 131),
        array('name' => "Salghum-al-'Ayd",'state_id' => 131),
        array('name' => "Sidi Maruf",'state_id' => 131),
        array('name' => "Sidi Marwan",'state_id' => 131),
        array('name' => "Tajananah",'state_id' => 131),
        array('name' => "Talighmah",'state_id' => 131),
        array('name' => "Wadi Athmaniyah",'state_id' => 131),
        array('name' => "Bu Khanifiyah",'state_id' => 132),
        array('name' => "Muaskar",'state_id' => 132),
        array('name' => "Muhammadiyah",'state_id' => 132),
        array('name' => "Siq",'state_id' => 132),
        array('name' => "Tighinnif",'state_id' => 132),
        array('name' => "Wadi al-Abtal",'state_id' => 132),
        array('name' => "Zahana",'state_id' => 132),
        array('name' => "'Ayn Tadalas",'state_id' => 133),
        array('name' => "Hassi Mamash",'state_id' => 133),
        array('name' => "Mazaghran",'state_id' => 133),
        array('name' => "Mustaghanam",'state_id' => 133),
        array('name' => "Sidi Ali",'state_id' => 133),
        array('name' => "'Ayn Safra",'state_id' => 134),
        array('name' => "Mishriyah",'state_id' => 134),
        array('name' => "Naama",'state_id' => 134),
        array('name' => "Oran",'state_id' => 135),
        array('name' => "Ouargla",'state_id' => 136),
        array('name' => "'Ayn Bardah",'state_id' => 137),
        array('name' => "Bumahra Ahmad",'state_id' => 137),
        array('name' => "Hamman Awlad 'Ali",'state_id' => 137),
        array('name' => "Qalmah",'state_id' => 137),
        array('name' => "Wadi Zinati",'state_id' => 137),
        array('name' => "'Ayn Abid",'state_id' => 138),
        array('name' => "'Ayn Samara",'state_id' => 138),
        array('name' => "Didush Murad",'state_id' => 138),
        array('name' => "Hamma Bu Ziyan",'state_id' => 138),
        array('name' => "Qustantinah",'state_id' => 138),
        array('name' => "Zighut Yusuf",'state_id' => 138),
        array('name' => "al-Khurub",'state_id' => 138),
        array('name' => "'Azzabah",'state_id' => 139),
        array('name' => "Amjaz Adshish",'state_id' => 139),
        array('name' => "Fil Fila",'state_id' => 139),
        array('name' => "Karkira",'state_id' => 139),
        array('name' => "Ramadan Jamal",'state_id' => 139),
        array('name' => "Sakikdah",'state_id' => 139),
        array('name' => "Shataybih",'state_id' => 139),
        array('name' => "Tamalus",'state_id' => 139),
        array('name' => "al-Harush",'state_id' => 139),
        array('name' => "al-Qull",'state_id' => 139),
        array('name' => "'Ayn 'Azl",'state_id' => 140),
        array('name' => "'Ayn Arnat",'state_id' => 140),
        array('name' => "'Ayn Taqrut",'state_id' => 140),
        array('name' => "'Ayn Wilman",'state_id' => 140),
        array('name' => "'Ayn-al-Khabira",'state_id' => 140),
        array('name' => "Bouira",'state_id' => 140),
        array('name' => "Buq'ah",'state_id' => 140),
        array('name' => "Salah Bay",'state_id' => 140),
        array('name' => "Satif",'state_id' => 140),
        array('name' => "Setif",'state_id' => 140),
        array('name' => "Ziyama Mansuriyah",'state_id' => 140),
        array('name' => "al-'Ulmah",'state_id' => 140),
        array('name' => "'Ayn-al-Hajar",'state_id' => 141),
        array('name' => "Sayda'",'state_id' => 141),
        array('name' => "'Ayn Qazzan",'state_id' => 144),
        array('name' => "'Ayn Salah",'state_id' => 144),
        array('name' => "Tamanghasat",'state_id' => 144),
        array('name' => "'Ayn Binyan",'state_id' => 145),
        array('name' => "Bu Isma'il",'state_id' => 145),
        array('name' => "Bu Midfar'ah",'state_id' => 145),
        array('name' => "Damus",'state_id' => 145),
        array('name' => "Duwirah",'state_id' => 145),
        array('name' => "Hajut",'state_id' => 145),
        array('name' => "Hammam Righa",'state_id' => 145),
        array('name' => "Sawlah",'state_id' => 145),
        array('name' => "Shiragha",'state_id' => 145),
        array('name' => "Shirshall",'state_id' => 145),
        array('name' => "Sidi Farj",'state_id' => 145),
        array('name' => "Stawali",'state_id' => 145),
        array('name' => "Tibazah",'state_id' => 145),
        array('name' => "Ziralda",'state_id' => 145),
        array('name' => "al-Qull'ah",'state_id' => 145),
        array('name' => "Bi'r-al-'Itir",'state_id' => 146),
        array('name' => "Hammamat",'state_id' => 146),
        array('name' => "Mursut",'state_id' => 146),
        array('name' => "Shariyah",'state_id' => 146),
        array('name' => "Tibissah",'state_id' => 146),
        array('name' => "Winzah",'state_id' => 146),
        array('name' => "al-'Awaynat",'state_id' => 146),
        array('name' => "Awlad Mimun",'state_id' => 147),
        array('name' => "Bani Mastar",'state_id' => 147),
        array('name' => "Bani Sikran",'state_id' => 147),
        array('name' => "Ghazawat",'state_id' => 147),
        array('name' => "Hannayah",'state_id' => 147),
        array('name' => "Maghniyah",'state_id' => 147),
        array('name' => "Nidruma",'state_id' => 147),
        array('name' => "Ramsh",'state_id' => 147),
        array('name' => "Sabra",'state_id' => 147),
        array('name' => "Shatwan",'state_id' => 147),
        array('name' => "Sibdu",'state_id' => 147),
        array('name' => "Sidi 'Abdallah",'state_id' => 147),
        array('name' => "Tilimsan",'state_id' => 147),
        array('name' => "al-Mansurah",'state_id' => 147),
        array('name' => "Tinduf",'state_id' => 148),
        array('name' => "Thaniyat-al-Had",'state_id' => 149),
        array('name' => "Tisamsilt",'state_id' => 149),
        array('name' => "'Ayn Dhahab",'state_id' => 150),
        array('name' => "Firindah",'state_id' => 150),
        array('name' => "Mahdiyah",'state_id' => 150),
        array('name' => "Mashra'a Asfa",'state_id' => 150),
        array('name' => "Qasr Shillalah",'state_id' => 150),
        array('name' => "Rahuyah",'state_id' => 150),
        array('name' => "Sughar",'state_id' => 150),
        array('name' => "Takhamarat",'state_id' => 150),
        array('name' => "Tiyarat",'state_id' => 150),
        array('name' => "'Ayn Bayda",'state_id' => 152),
        array('name' => "'Ayn Fakrun",'state_id' => 152),
        array('name' => "'Ayn Kirshah",'state_id' => 152),
        array('name' => "'Ayn Malilah",'state_id' => 152),
        array('name' => "Bi'r Shuhada",'state_id' => 152),
        array('name' => "Miskyanah",'state_id' => 152),
        array('name' => "Shamurah",'state_id' => 152),
        array('name' => "Umm-al-Bawaghi",'state_id' => 152),
        array('name' => "'Ayn Biya",'state_id' => 153),
        array('name' => "'Ayn-at-Turk",'state_id' => 153),
        array('name' => "Arzu",'state_id' => 153),
        array('name' => "Bi'r-al-Jir",'state_id' => 153),
        array('name' => "Butlilis",'state_id' => 153),
        array('name' => "Hassi Bu Nif",'state_id' => 153),
        array('name' => "Mars-al-Kabir",'state_id' => 153),
        array('name' => "Qadayal",'state_id' => 153),
        array('name' => "Sidi ash-Shami",'state_id' => 153),
        array('name' => "Wadi Thalatha",'state_id' => 153),
        array('name' => "Wahran",'state_id' => 153),
        array('name' => "al-Ansur",'state_id' => 153),
        array('name' => "as-Saniyah",'state_id' => 153),
        array('name' => "Hassi Mas'ud",'state_id' => 154),
        array('name' => "Nazla",'state_id' => 154),
        array('name' => "Ruwisiyat",'state_id' => 154),
        array('name' => "Tabisbast",'state_id' => 154),
        array('name' => "Tamalhat",'state_id' => 154),
        array('name' => "Tamasin",'state_id' => 154),
        array('name' => "Tayabat-al-Janubiyah",'state_id' => 154),
        array('name' => "Tughghurt",'state_id' => 154),
        array('name' => "Warqla",'state_id' => 154),
        array('name' => "al-Hajirah",'state_id' => 154),
        array('name' => "Aflu",'state_id' => 158),
        array('name' => "Hassi al-Raml",'state_id' => 158),
        array('name' => "al-Aghwat",'state_id' => 158),
        array('name' => "Brizyanah",'state_id' => 159),
        array('name' => "al-Abyad Sidi Shaykh",'state_id' => 159),
        array('name' => "al-Bayadh",'state_id' => 159),
        array('name' => "Bab Azwar",'state_id' => 160),
        array('name' => "Baraki",'state_id' => 160),
        array('name' => "Bir Murad Rais",'state_id' => 160),
        array('name' => "Birkhadam",'state_id' => 160),
        array('name' => "Burj-al-Kiffan",'state_id' => 160),
        array('name' => "Dar-al-Bayda",'state_id' => 160),
        array('name' => "al-Jaza'ir",'state_id' => 160),
        array('name' => "Bayadha",'state_id' => 161),
        array('name' => "Dabilah",'state_id' => 161),
        array('name' => "Hassan 'Abd-al-Karim",'state_id' => 161),
        array('name' => "Hassi Halifa",'state_id' => 161),
        array('name' => "Jama'a",'state_id' => 161),
        array('name' => "Maqran",'state_id' => 161),
        array('name' => "Qamar",'state_id' => 161),
        array('name' => "Raqiba",'state_id' => 161),
        array('name' => "Rubbah",'state_id' => 161),
        array('name' => "Sidi Amran",'state_id' => 161),
        array('name' => "al-Mighair",'state_id' => 161),
        array('name' => "al-Wad",'state_id' => 161),
        array('name' => "'Ayn Maran",'state_id' => 162),
        array('name' => "Abu al-Hassan",'state_id' => 162),
        array('name' => "Bani Hawa",'state_id' => 162),
        array('name' => "Bu Qadir",'state_id' => 162),
        array('name' => "Sidi Ukaskah",'state_id' => 162),
        array('name' => "Tanas",'state_id' => 162),
        array('name' => "Wadi Sali",'state_id' => 162),
        array('name' => "Wadi al-Fiddah",'state_id' => 162),
        array('name' => "ash-Shalif",'state_id' => 162),
        array('name' => "ash-Shattiyah",'state_id' => 162),
        array('name' => "Ban Mahdi",'state_id' => 163),
        array('name' => "Bani Amar",'state_id' => 163),
        array('name' => "Basbas",'state_id' => 163),
        array('name' => "Dariyan",'state_id' => 163),
        array('name' => "Saba'ita Muk",'state_id' => 163),
        array('name' => "al-Qal'ah",'state_id' => 163),
        array('name' => "at-Tarif",'state_id' => 163),
        array('name' => "Afono",'state_id' => 164),
        array('name' => "Alao",'state_id' => 164),
        array('name' => "Alofau",'state_id' => 164),
        array('name' => "Amouli",'state_id' => 164),
        array('name' => "Aoa",'state_id' => 164),
        array('name' => "Atu'u",'state_id' => 164),
        array('name' => "Aua",'state_id' => 164),
        array('name' => "Aunu'u",'state_id' => 164),
        array('name' => "Faga'alu",'state_id' => 164),
        array('name' => "Faga'itua",'state_id' => 164),
        array('name' => "Fagasa",'state_id' => 164),
        array('name' => "Fagatogo",'state_id' => 164),
        array('name' => "Lauli'i",'state_id' => 164),
        array('name' => "Leloaloa",'state_id' => 164),
        array('name' => "Nu'uuli",'state_id' => 164),
        array('name' => "Pago Pago",'state_id' => 164),
        array('name' => "Tula",'state_id' => 164),
        array('name' => "Utulei",'state_id' => 164),
        array('name' => "Vatia",'state_id' => 164),
        array('name' => "Ofu",'state_id' => 165),
        array('name' => "Aoloau",'state_id' => 167),
        array('name' => "Faleniu",'state_id' => 167),
        array('name' => "Futiga",'state_id' => 167),
        array('name' => "Ili'ili",'state_id' => 167),
        array('name' => "Leone",'state_id' => 167),
        array('name' => "Malaeimi",'state_id' => 167),
        array('name' => "Malaeloa-Aitulagi",'state_id' => 167),
        array('name' => "Malaeloa-Ituau",'state_id' => 167),
        array('name' => "Mapusagafou",'state_id' => 167),
        array('name' => "Mesepa",'state_id' => 167),
        array('name' => "Pava'ia'i",'state_id' => 167),
        array('name' => "Tafuna",'state_id' => 167),
        array('name' => "Taputimu",'state_id' => 167),
        array('name' => "Vailoatai",'state_id' => 167),
        array('name' => "Vaitogi",'state_id' => 167),
        array('name' => "Canillo",'state_id' => 169),
        array('name' => "Encamp",'state_id' => 170),
        array('name' => "Ordino",'state_id' => 173),
        array('name' => "Caxito",'state_id' => 175),
        array('name' => "Benguela",'state_id' => 176),
        array('name' => "Lobito",'state_id' => 176),
        array('name' => "Camacupa",'state_id' => 177),
        array('name' => "Kuito",'state_id' => 177),
        array('name' => "Cabinda",'state_id' => 178),
        array('name' => "Ondjiva",'state_id' => 179),
        array('name' => "Caala",'state_id' => 180),
        array('name' => "Catchiungo",'state_id' => 180),
        array('name' => "Huambo",'state_id' => 180),
        array('name' => "Longonjo",'state_id' => 180),
        array('name' => "Caconda",'state_id' => 181),
        array('name' => "Caluquembe",'state_id' => 181),
        array('name' => "Lubango",'state_id' => 181),
        array('name' => "Menongue",'state_id' => 182),
        array('name' => "Luanda",'state_id' => 185),
        array('name' => "Malanje",'state_id' => 188),
        array('name' => "Cazaje",'state_id' => 189),
        array('name' => "Leua",'state_id' => 189),
        array('name' => "Luau",'state_id' => 189),
        array('name' => "Luena",'state_id' => 189),
        array('name' => "Lumeje",'state_id' => 189),
        array('name' => "Namibe",'state_id' => 190),
        array('name' => "Camabatela",'state_id' => 191),
        array('name' => "Uige",'state_id' => 191),
        array('name' => "M'banza-Kongo",'state_id' => 192),
        array('name' => "N'zeto",'state_id' => 192),
        array('name' => "Soyo",'state_id' => 192),
        array('name' => "Codrington",'state_id' => 201),
        array('name' => "Catamarca",'state_id' => 209),
        array('name' => "Presidencia Roque Saenz Pena",'state_id' => 210),
        array('name' => "Resistencia",'state_id' => 210),
        array('name' => "Comodoro Rivadavia",'state_id' => 211),
        array('name' => "Puerto Madryn",'state_id' => 211),
        array('name' => "Rawson",'state_id' => 211),
        array('name' => "Trelew",'state_id' => 211),
        array('name' => "Alta Gracia",'state_id' => 212),
        array('name' => "Bell Ville",'state_id' => 212),
        array('name' => "Cordoba",'state_id' => 212),
        array('name' => "Rio Cuarto",'state_id' => 212),
        array('name' => "Rio Tercero",'state_id' => 212),
        array('name' => "San Francisco",'state_id' => 212),
        array('name' => "Villa Carlos Paz",'state_id' => 212),
        array('name' => "Villa Maria",'state_id' => 212),
        array('name' => "Corrientes",'state_id' => 213),
        array('name' => "Goya",'state_id' => 213),
        array('name' => "Mercedes",'state_id' => 213),
        array('name' => "San Lorenzo",'state_id' => 213),
        array('name' => "Formosa",'state_id' => 216),
        array('name' => "Jujuy",'state_id' => 217),
        array('name' => "Libertador General San Martin",'state_id' => 217),
        array('name' => "San Pedro",'state_id' => 217),
        array('name' => "Godoy Cruz",'state_id' => 220),
        array('name' => "Lujan",'state_id' => 220),
        array('name' => "Mendoza",'state_id' => 220),
        array('name' => "Rivadavia",'state_id' => 220),
        array('name' => "San Martin",'state_id' => 220),
        array('name' => "San Rafael",'state_id' => 220),
        array('name' => "Eldorado",'state_id' => 221),
        array('name' => "Obera",'state_id' => 221),
        array('name' => "Posadas",'state_id' => 221),
        array('name' => "Cutral Co",'state_id' => 222),
        array('name' => "Neuquen",'state_id' => 222),
        array('name' => "Salta",'state_id' => 224),
        array('name' => "San Ramon de la Nueva Oran",'state_id' => 224),
        array('name' => "Tartagal",'state_id' => 224),
        array('name' => "Tucuman",'state_id' => 231),
    );
    
    DB::table('cities')->insert($cities);
    }
}
