<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('states')->delete();
        $states = array(
            array('name' => "Andaman and Nicobar Islands",'country_id' => 11),
            array('name' => "Andhra Pradesh",'country_id' => 11),
            array('name' => "Arunachal Pradesh",'country_id' => 11),
            array('name' => "Assam",'country_id' => 11),
            array('name' => "Bihar",'country_id' => 11),
            array('name' => "Chandigarh",'country_id' => 11),
            array('name' => "Chhattisgarh",'country_id' => 11),
            array('name' => "Dadra and Nagar Haveli",'country_id' => 11),
            array('name' => "Daman and Diu",'country_id' => 11),
            array('name' => "Delhi",'country_id' => 11),
            array('name' => "Goa",'country_id' => 11),
            array('name' => "Gujarat",'country_id' => 11),
            array('name' => "Haryana",'country_id' => 11),
            array('name' => "Himachal Pradesh",'country_id' => 11),
            array('name' => "Jammu and Kashmir",'country_id' => 11),
            array('name' => "Jharkhand",'country_id' => 11),
            array('name' => "Karnataka",'country_id' => 11),
            array('name' => "Kenmore",'country_id' => 11),
            array('name' => "Kerala",'country_id' => 11),
            array('name' => "Lakshadweep",'country_id' => 11),
            array('name' => "Madhya Pradesh",'country_id' => 11),
            array('name' => "Maharashtra",'country_id' => 11),
            array('name' => "Manipur",'country_id' => 11),
            array('name' => "Meghalaya",'country_id' => 11),
            array('name' => "Mizoram",'country_id' => 11),
            array('name' => "Nagaland",'country_id' => 11),
            array('name' => "Narora",'country_id' => 11),
            array('name' => "Natwar",'country_id' => 11),
            array('name' => "Odisha",'country_id' => 11),
            array('name' => "Paschim Medinipur",'country_id' => 11),
            array('name' => "Pondicherry",'country_id' => 11),
            array('name' => "Punjab",'country_id' => 11),
            array('name' => "Rajasthan",'country_id' => 11),
            array('name' => "Sikkim",'country_id' => 11),
            array('name' => "Tamil Nadu",'country_id' => 11),
            array('name' => "Telangana",'country_id' => 11),
            array('name' => "Tripura",'country_id' => 11),
            array('name' => "Uttar Pradesh",'country_id' => 11),
            array('name' => "Uttarakhand",'country_id' => 11),
            array('name' => "Vaishali",'country_id' => 11),
            array('name' => "West Bengal",'country_id' => 11),    
            array('name' => "Badakhshan",'country_id' => 1),
            array('name' => "Badgis",'country_id' => 1),
            array('name' => "Baglan",'country_id' => 1),
            array('name' => "Balkh",'country_id' => 1),
            array('name' => "Bamiyan",'country_id' => 1),
            array('name' => "Farah",'country_id' => 1),
            array('name' => "Faryab",'country_id' => 1),
            array('name' => "Gawr",'country_id' => 1),
            array('name' => "Gazni",'country_id' => 1),
            array('name' => "Herat",'country_id' => 1),
            array('name' => "Hilmand",'country_id' => 1),
            array('name' => "Jawzjan",'country_id' => 1),
            array('name' => "Kabul",'country_id' => 1),
            array('name' => "Kapisa",'country_id' => 1),
            array('name' => "Khawst",'country_id' => 1),
            array('name' => "Kunar",'country_id' => 1),
            array('name' => "Lagman",'country_id' => 1),
            array('name' => "Lawghar",'country_id' => 1),
            array('name' => "Nangarhar",'country_id' => 1),
            array('name' => "Nimruz",'country_id' => 1),
            array('name' => "Nuristan",'country_id' => 1),
            array('name' => "Paktika",'country_id' => 1),
            array('name' => "Paktiya",'country_id' => 1),
            array('name' => "Parwan",'country_id' => 1),
            array('name' => "Qandahar",'country_id' => 1),
            array('name' => "Qunduz",'country_id' => 1),
            array('name' => "Samangan",'country_id' => 1),
            array('name' => "Sar-e Pul",'country_id' => 1),
            array('name' => "Takhar",'country_id' => 1),
            array('name' => "Uruzgan",'country_id' => 1),
            array('name' => "Wardak",'country_id' => 1),
            array('name' => "Zabul",'country_id' => 1),
            array('name' => "Berat",'country_id' => 2),
            array('name' => "Bulqize",'country_id' => 2),
            array('name' => "Delvine",'country_id' => 2),
            array('name' => "Devoll",'country_id' => 2),
            array('name' => "Dibre",'country_id' => 2),
            array('name' => "Durres",'country_id' => 2),
            array('name' => "Elbasan",'country_id' => 2),
            array('name' => "Fier",'country_id' => 2),
            array('name' => "Gjirokaster",'country_id' => 2),
            array('name' => "Gramsh",'country_id' => 2),
            array('name' => "Has",'country_id' => 2),
            array('name' => "Kavaje",'country_id' => 2),
            array('name' => "Kolonje",'country_id' => 2),
            array('name' => "Korce",'country_id' => 2),
            array('name' => "Kruje",'country_id' => 2),
            array('name' => "Kucove",'country_id' => 2),
            array('name' => "Kukes",'country_id' => 2),
            array('name' => "Kurbin",'country_id' => 2),
            array('name' => "Lezhe",'country_id' => 2),
            array('name' => "Librazhd",'country_id' => 2),
            array('name' => "Lushnje",'country_id' => 2),
            array('name' => "Mallakaster",'country_id' => 2),
            array('name' => "Malsi e Madhe",'country_id' => 2),
            array('name' => "Mat",'country_id' => 2),
            array('name' => "Mirdite",'country_id' => 2),
            array('name' => "Peqin",'country_id' => 2),
            array('name' => "Permet",'country_id' => 2),
            array('name' => "Pogradec",'country_id' => 2),
            array('name' => "Puke",'country_id' => 2),
            array('name' => "Sarande",'country_id' => 2),
            array('name' => "Shkoder",'country_id' => 2),
            array('name' => "Skrapar",'country_id' => 2),
            array('name' => "Tepelene",'country_id' => 2),
            array('name' => "Tirane",'country_id' => 2),
            array('name' => "Tropoje",'country_id' => 2),
            array('name' => "Vlore",'country_id' => 2),
            array('name' => "'Ayn Daflah",'country_id' => 3),
            array('name' => "'Ayn Tamushanat",'country_id' => 3),
            array('name' => "Adrar",'country_id' => 3),
            array('name' => "Algiers",'country_id' => 3),
            array('name' => "Annabah",'country_id' => 3),
            array('name' => "Bashshar",'country_id' => 3),
            array('name' => "Batnah",'country_id' => 3),
            array('name' => "Bijayah",'country_id' => 3),
            array('name' => "Biskrah",'country_id' => 3),
            array('name' => "Blidah",'country_id' => 3),
            array('name' => "Buirah",'country_id' => 3),
            array('name' => "Bumardas",'country_id' => 3),
            array('name' => "Burj Bu Arririj",'country_id' => 3),
            array('name' => "Ghalizan",'country_id' => 3),
            array('name' => "Ghardayah",'country_id' => 3),
            array('name' => "Ilizi",'country_id' => 3),
            array('name' => "Jijili",'country_id' => 3),
            array('name' => "Jilfah",'country_id' => 3),
            array('name' => "Khanshalah",'country_id' => 3),
            array('name' => "Masilah",'country_id' => 3),
            array('name' => "Midyah",'country_id' => 3),
            array('name' => "Milah",'country_id' => 3),
            array('name' => "Muaskar",'country_id' => 3),
            array('name' => "Mustaghanam",'country_id' => 3),
            array('name' => "Naama",'country_id' => 3),
            array('name' => "Oran",'country_id' => 3),
            array('name' => "Ouargla",'country_id' => 3),
            array('name' => "Qalmah",'country_id' => 3),
            array('name' => "Qustantinah",'country_id' => 3),
            array('name' => "Sakikdah",'country_id' => 3),
            array('name' => "Satif",'country_id' => 3),
            array('name' => "Sayda'",'country_id' => 3),
            array('name' => "Sidi ban-al-'Abbas",'country_id' => 3),
            array('name' => "Suq Ahras",'country_id' => 3),
            array('name' => "Tamanghasat",'country_id' => 3),
            array('name' => "Tibazah",'country_id' => 3),
            array('name' => "Tibissah",'country_id' => 3),
            array('name' => "Tilimsan",'country_id' => 3),
            array('name' => "Tinduf",'country_id' => 3),
            array('name' => "Tisamsilt",'country_id' => 3),
            array('name' => "Tiyarat",'country_id' => 3),
            array('name' => "Tizi Wazu",'country_id' => 3),
            array('name' => "Umm-al-Bawaghi",'country_id' => 3),
            array('name' => "Wahran",'country_id' => 3),
            array('name' => "Warqla",'country_id' => 3),
            array('name' => "Wilaya d Alger",'country_id' => 3),
            array('name' => "Wilaya de Bejaia",'country_id' => 3),
            array('name' => "Wilaya de Constantine",'country_id' => 3),
            array('name' => "al-Aghwat",'country_id' => 3),
            array('name' => "al-Bayadh",'country_id' => 3),
            array('name' => "al-Jaza'ir",'country_id' => 3),
            array('name' => "al-Wad",'country_id' => 3),
            array('name' => "ash-Shalif",'country_id' => 3),
            array('name' => "at-Tarif",'country_id' => 3),
            array('name' => "Eastern",'country_id' => 4),
            array('name' => "Manu'a",'country_id' => 4),
            array('name' => "Swains Island",'country_id' => 4),
            array('name' => "Western",'country_id' => 4),
            array('name' => "Andorra la Vella",'country_id' => 5),
            array('name' => "Canillo",'country_id' => 5),
            array('name' => "Encamp",'country_id' => 5),
            array('name' => "La Massana",'country_id' => 5),
            array('name' => "Les Escaldes",'country_id' => 5),
            array('name' => "Ordino",'country_id' => 5),
            array('name' => "Sant Julia de Loria",'country_id' => 5),
            array('name' => "Bengo",'country_id' => 6),
            array('name' => "Benguela",'country_id' => 6),
            array('name' => "Bie",'country_id' => 6),
            array('name' => "Cabinda",'country_id' => 6),
            array('name' => "Cunene",'country_id' => 6),
            array('name' => "Huambo",'country_id' => 6),
            array('name' => "Huila",'country_id' => 6),
            array('name' => "Kuando-Kubango",'country_id' => 6),
            array('name' => "Kwanza Norte",'country_id' => 6),
            array('name' => "Kwanza Sul",'country_id' => 6),
            array('name' => "Luanda",'country_id' => 6),
            array('name' => "Lunda Norte",'country_id' => 6),
            array('name' => "Lunda Sul",'country_id' => 6),
            array('name' => "Malanje",'country_id' => 6),
            array('name' => "Moxico",'country_id' => 6),
            array('name' => "Namibe",'country_id' => 6),
            array('name' => "Uige",'country_id' => 6),
            array('name' => "Zaire",'country_id' => 6),
            array('name' => "Other Provinces",'country_id' => 7),
            array('name' => "Sector claimed by Argentina/Ch",'country_id' => 8),
            array('name' => "Sector claimed by Argentina/UK",'country_id' => 8),
            array('name' => "Sector claimed by Australia",'country_id' => 8),
            array('name' => "Sector claimed by France",'country_id' => 8),
            array('name' => "Sector claimed by New Zealand",'country_id' => 8),
            array('name' => "Sector claimed by Norway",'country_id' => 8),
            array('name' => "Unclaimed Sector",'country_id' => 8),
            array('name' => "Barbuda",'country_id' => 9),
            array('name' => "Saint George",'country_id' => 9),
            array('name' => "Saint John",'country_id' => 9),
            array('name' => "Saint Mary",'country_id' => 9),
            array('name' => "Saint Paul",'country_id' => 9),
            array('name' => "Saint Peter",'country_id' => 9),
            array('name' => "Saint Philip",'country_id' => 9),
            array('name' => "Buenos Aires",'country_id' => 10),
            array('name' => "Catamarca",'country_id' => 10),
            array('name' => "Chaco",'country_id' => 10),
            array('name' => "Chubut",'country_id' => 10),
            array('name' => "Cordoba",'country_id' => 10),
            array('name' => "Corrientes",'country_id' => 10),
            array('name' => "Distrito Federal",'country_id' => 10),
            array('name' => "Entre Rios",'country_id' => 10),
            array('name' => "Formosa",'country_id' => 10),
            array('name' => "Jujuy",'country_id' => 10),
            array('name' => "La Pampa",'country_id' => 10),
            array('name' => "La Rioja",'country_id' => 10),
            array('name' => "Mendoza",'country_id' => 10),
            array('name' => "Misiones",'country_id' => 10),
            array('name' => "Neuquen",'country_id' => 10),
            array('name' => "Rio Negro",'country_id' => 10),
            array('name' => "Salta",'country_id' => 10),
            array('name' => "San Juan",'country_id' => 10),
            array('name' => "San Luis",'country_id' => 10),
            array('name' => "Santa Cruz",'country_id' => 10),
            array('name' => "Santa Fe",'country_id' => 10),
            array('name' => "Santiago del Estero",'country_id' => 10),
            array('name' => "Tierra del Fuego",'country_id' => 10),
            array('name' => "Tucuman",'country_id' => 10),
        );
		DB::table('states')->insert($states);
           
    }
}
